name: 'json-to-sarif-actions'
description: 'json-to-sarif-actions'
inputs:

  json_file_path:  # id of input
    description: 'json_file_path path'
    required: true
    default: './license-go.json'
  licens_sarif_name:  # id of input
    description: 'licens_sarif name'
    required: true
    default: './1.sarif'
outputs:
  result_str: # id of output
    description: 'The result_str '
runs:
  using: "composite"
  steps: 
  
    #- run: chmod +x ${{ github.action_path }}/json-to-sarif-actions.sh;${{ github.action_path }}/json-to-sarif-actions.sh  ${{ inputs.json_file_path }} ${{ inputs.licens_sarif_name }}
    - run: chmod +x ${{ github.action_path }}/json-to-sarif-actions.py;python ${{ github.action_path }}/json-to-sarif-actions.py  ${{ inputs.json_file_path }} ${{ inputs.licens_sarif_name }}
      shell: bash
