name: 'json-to-sarif-actions'
description: 'Greet someone and record the time'
inputs:
  json_file:  # id of input
    description: 'json_file path'
    required: true
    default: 'license-go.json'
outputs:
  result_str: # id of output
    description: 'The result_str '
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.json_file }}
