#!/bin/bash
#name=$1
json_file_path=$1
licens_sarif_path=$2

head=""

#json_file_path=$(cat license-go.json | sed 's/[[:space:]]//g' | sed 's/"/\\"/g' ) 

json_str=$(cat ${json_file_path} | sed 's/[[:space:]]//g' | sed 's/"/\\"/g' ) 
echo -e $json_str

#head='{ "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json", "version": "2.1.0", "properties": { "comment": "This sample demonstrates the use of default rule configuration." }, "runs": [ { "tool": { "driver": { "name": "SarifSamples", "version": "1.0", "rules": [ { "id": "TUT0001", "defaultConfiguration": { "level": "warning", "properties": { "comment": "'"'warning' is the default, so this can be omitted.\" } } } ] } }, \"results\": [ { \"ruleId\": \"TUT1001\", \"ruleIndex\": 0, \"message\": { \"text\": \"${json_str}\" }, \"locations\": [ { \"physicalLocation\": { \"artifactLocation\": { \"uri\": \"licens.sarif\" } } } ] } ], \"columnKind\": \"utf16CodeUnits\" } ] }"
#head='{ "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json", "version": "2.1.0", "properties": { "comment": "This sample demonstrates the use of default rule configuration." }, "runs": [ { "tool": { "driver": { "name": "dep-scan", "version": "1.0", "rules": [ { "id": "TUT0001", "defaultConfiguration": { "level": "warning", "properties": { "comment": "'"'warning' is the default, so this can be omitted.\" } } } ] } }, \"results\": [ { \"ruleId\": \"TUT1001\", \"ruleIndex\": 0, \"message\": { \"text\": \"${json_str}\" }, \"locations\": [ { \"physicalLocation\": { \"artifactLocation\": { \"uri\": \"${licens_sarif_path}\" } } } ] } ], \"columnKind\": \"utf16CodeUnits\" } ] }"
head='"{ \"$schema\": \"https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.4.json\", \"version\": \"2.1.0\", \"runs\": [ { \"tool\": { \"driver\": { \"name\": \"Anchore Container Vulnerability Report (T0)\", \"fullName\": \"Anchore Container Vulnerability Report (T0)\", \"version\": \"0.5.0\", \"semanticVersion\": \"0.5.0\", \"dottedQuadFileVersion\": \"0.5.0.0\", \"rules\": [ { \"id\": \"ANCHOREVULN_CVE-2015-8768_python_click_1.1.1\", \"shortDescription\": { \"text\": \"CVE-2015-8768 Severity=Critical Package=click Version=1.1.1\" }, \"fullDescription\": { \"text\": \"CVE-2015-8768 Severity=Critical Package=click Version=1.1.1\" }, \"help\": { \"text\": \"Vulnerability CVE-2015-8768\nSeverity: Critical\nPackage: click\nVersion: 1.1.1\nFix Version: unknown\nType: python\nLocation: tests/python/setup.py\nData Namespace: unknown\nLink: [CVE-2015-8768](http://bazaar.launchpad.net/~click-hackers/click/devel/revision/587)\", \"markdown\": \"**Vulnerability CVE-2015-8768**\n| Severity | Package | Version | Fix Version | Type | Location | Data Namespace | Link |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n|Critical|click|1.1.1|unknown|python|tests/python/setup.py|unknown|[CVE-2015-8768](http://bazaar.launchpad.net/~click-hackers/click/devel/revision/587)|\n\" } } ] } }, \"logicalLocations\": [ { \"name\": \"dockerfile\", \"fullyQualifiedName\": \"dockerfile\", \"kind\": \"namespace\" } ], \"results\": [ { \"ruleId\": \"ANCHOREVULN_CVE-2015-8768_python_click_1.1.1\", \"ruleIndex\": 0, \"level\": \"error\", \"message\": { \"text\": \"The path tests/python/setup.py would result in an installed vulnerability: (click type=python)\", \"id\": \"default\" }, \"analysisTarget\": { \"uri\": \"tests/python/setup.py\" }, \"locations\": [ { \"physicalLocation\": { \"artifactLocation\": { \"uri\": \"tests/python/setup.py\" }, \"region\": { \"startLine\": 1, \"startColumn\": 1, \"endLine\": 1, \"endColumn\": 1, \"byteOffset\": 1, \"byteLength\": 1 } }, \"logicalLocations\": [ { \"fullyQualifiedName\": \"dockerfile\" } ] } ], \"suppressions\": [ { \"kind\": \"external\" } ], \"baselineState\": \"unchanged\" }, { \"ruleId\": \"ANCHOREVULN_CVE-2015-8768_python_click_1.1.1\", \"ruleIndex\": 0, \"level\": \"error\", \"message\": { \"text\": \"The path tests/python/setup.py would result in an installed vulnerability: (click type=python)\", \"id\": \"default\" }, \"analysisTarget\": { \"uri\": \"tests/python/setup.py\" }, \"locations\": [ { \"physicalLocation\": { \"artifactLocation\": { \"uri\": \"tests/python/setup.py\" }, \"region\": { \"startLine\": 1, \"startColumn\": 1, \"endLine\": 1, \"endColumn\": 1, \"byteOffset\": 1, \"byteLength\": 1 } }, \"logicalLocations\": [ { \"fullyQualifiedName\": \"dockerfile\" } ] } ], \"suppressions\": [ { \"kind\": \"external\" } ], \"baselineState\": \"unchanged\" } ], \"columnKind\": \"utf16CodeUnits\" } ] }"'
#echo  $head | sed 's/} {/}\\n{/g'>1.sarif
echo  $head | sed 's/} {/}\\n{/g'>${licens_sarif_path}
